Rails:
  Enabled: true

AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'out/**/*'
    - 'bin/*'
    - 'test/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Style/ClassAndModuleChildren:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/AbcSize:
  Max: 90

Metrics/ClassLength:
  Max: 300

Metrics/CyclomaticComplexity:
  Max: 9

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 60

Metrics/ModuleLength:
  Max: 300
  Exclude:
    - "**/*_spec.rb"

Metrics/PerceivedComplexity:
  Max: 11

Metrics/BlockLength:
  Max: 60
  Exclude:
    - "**/*_spec.rb"

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/Validation:
  Exclude:
    - 'app/models/user.rb'
